#include<Gear/Core/FMT.h>

namespace Gear::Core::FMT
{
	uint32_t getByteSize(const DXGI_FORMAT format)
	{
		switch (format)
		{
		case RGBA32TL:
		case RGBA32F:
		case RGBA32UI:
		case RGBA32I:
			return 16;

		case RGB32TL:
		case RGB32F:
		case RGB32UI:
		case RGB32I:
			return 12;

		case RGBA16TL:
		case RGBA16F:
		case RGBA16UN:
		case RGBA16UI:
		case RGBA16SN:
		case RGBA16I:
		case RG32TL:
		case RG32F:
		case RG32UI:
		case RG32I:
		case DXGI_FORMAT_R32G8X24_TYPELESS:
		case DXGI_FORMAT_D32_FLOAT_S8X24_UINT:
		case DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS:
		case DXGI_FORMAT_X32_TYPELESS_G8X24_UINT:
		case DXGI_FORMAT_Y416:
		case DXGI_FORMAT_Y210:
		case DXGI_FORMAT_Y216:
			return 8;

		case DXGI_FORMAT_R10G10B10A2_TYPELESS:
		case DXGI_FORMAT_R10G10B10A2_UNORM:
		case DXGI_FORMAT_R10G10B10A2_UINT:
		case RG11B10F:
		case RGBA8TL:
		case RGBA8UN:
		case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:
		case RGBA8UI:
		case RGBA8SN:
		case RGBA8I:
		case RG16TL:
		case RG16F:
		case RG16UN:
		case RG16UI:
		case RG16SN:
		case RG16I:
		case R32TL:
		case D32F:
		case R32F:
		case R32UI:
		case R32I:
		case DXGI_FORMAT_R24G8_TYPELESS:
		case DXGI_FORMAT_D24_UNORM_S8_UINT:
		case DXGI_FORMAT_R24_UNORM_X8_TYPELESS:
		case DXGI_FORMAT_X24_TYPELESS_G8_UINT:
		case DXGI_FORMAT_R9G9B9E5_SHAREDEXP:
		case DXGI_FORMAT_R8G8_B8G8_UNORM:
		case DXGI_FORMAT_G8R8_G8B8_UNORM:
		case BGRA8UN:
		case DXGI_FORMAT_B8G8R8X8_UNORM:
		case DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM:
		case DXGI_FORMAT_B8G8R8A8_TYPELESS:
		case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB:
		case DXGI_FORMAT_B8G8R8X8_TYPELESS:
		case DXGI_FORMAT_B8G8R8X8_UNORM_SRGB:
		case DXGI_FORMAT_AYUV:
		case DXGI_FORMAT_Y410:
		case DXGI_FORMAT_YUY2:
			return 4;

		case DXGI_FORMAT_P010:
		case DXGI_FORMAT_P016:
		case DXGI_FORMAT_V408:
			return 3;

		case RG8TL:
		case RG8UN:
		case RG8UI:
		case RG8SN:
		case RG8I:
		case R16TL:
		case R16F:
		case D16UN:
		case R16UN:
		case R16UI:
		case R16SN:
		case R16I:
		case DXGI_FORMAT_B5G6R5_UNORM:
		case DXGI_FORMAT_B5G5R5A1_UNORM:
		case DXGI_FORMAT_A8P8:
		case DXGI_FORMAT_B4G4R4A4_UNORM:
		case DXGI_FORMAT_P208:
		case DXGI_FORMAT_V208:
			return 2;

		case R8TL:
		case R8UN:
		case R8UI:
		case R8SN:
		case R8I:
		case DXGI_FORMAT_A8_UNORM:
		case DXGI_FORMAT_BC2_TYPELESS:
		case DXGI_FORMAT_BC2_UNORM:
		case DXGI_FORMAT_BC2_UNORM_SRGB:
		case DXGI_FORMAT_BC3_TYPELESS:
		case DXGI_FORMAT_BC3_UNORM:
		case DXGI_FORMAT_BC3_UNORM_SRGB:
		case DXGI_FORMAT_BC5_TYPELESS:
		case DXGI_FORMAT_BC5_UNORM:
		case DXGI_FORMAT_BC5_SNORM:
		case DXGI_FORMAT_BC6H_TYPELESS:
		case DXGI_FORMAT_BC6H_UF16:
		case DXGI_FORMAT_BC6H_SF16:
		case DXGI_FORMAT_BC7_TYPELESS:
		case DXGI_FORMAT_BC7_UNORM:
		case DXGI_FORMAT_BC7_UNORM_SRGB:
		case DXGI_FORMAT_AI44:
		case DXGI_FORMAT_IA44:
		case DXGI_FORMAT_P8:
			return 1;

		default:
			return 0;
		}
	}
}
