#pragma once

#ifndef _GEAR_CORE_FMT_H_
#define _GEAR_CORE_FMT_H_

/// <summary>
/// 我最开始学习的是OpenGL，非常喜欢里面资源格式的命名
/// 我于是仿照OpenGL资源格式的命名规范，在这个头文件里增加了一些常用DXGI_FORMAT的别名
/// 这也是我在我的D3D11老项目中做的事，它带来的改善是非常大的，日常敲代码轻松太多了
/// </summary>

#include<cstdint>

#include<D3D12Headers/dxgiformat.h>

/// <summary>
/// 通道顺序 + 每通道比特 + 类型
/// </summary>
namespace Gear::Core::FMT
{
	//有符号整形
	constexpr DXGI_FORMAT R8SI = DXGI_FORMAT_R8_SINT;
	constexpr DXGI_FORMAT RG8SI = DXGI_FORMAT_R8G8_SINT;
	constexpr DXGI_FORMAT RGBA8SI = DXGI_FORMAT_R8G8B8A8_SINT;

	constexpr DXGI_FORMAT R16SI = DXGI_FORMAT_R16_SINT;
	constexpr DXGI_FORMAT RG16SI = DXGI_FORMAT_R16G16_SINT;
	constexpr DXGI_FORMAT RGBA16SI = DXGI_FORMAT_R16G16B16A16_SINT;

	constexpr DXGI_FORMAT R32SI = DXGI_FORMAT_R32_SINT;
	constexpr DXGI_FORMAT RG32SI = DXGI_FORMAT_R32G32_SINT;
	constexpr DXGI_FORMAT RGB32SI = DXGI_FORMAT_R32G32B32_SINT;
	constexpr DXGI_FORMAT RGBA32SI = DXGI_FORMAT_R32G32B32A32_SINT;

	//无符号整形
	constexpr DXGI_FORMAT R8UI = DXGI_FORMAT_R8_UINT;
	constexpr DXGI_FORMAT RG8UI = DXGI_FORMAT_R8G8_UINT;
	constexpr DXGI_FORMAT RGBA8UI = DXGI_FORMAT_R8G8B8A8_UINT;

	constexpr DXGI_FORMAT R16UI = DXGI_FORMAT_R16_UINT;
	constexpr DXGI_FORMAT RG16UI = DXGI_FORMAT_R16G16_UINT;
	constexpr DXGI_FORMAT RGBA16UI = DXGI_FORMAT_R16G16B16A16_UINT;

	constexpr DXGI_FORMAT R32UI = DXGI_FORMAT_R32_UINT;
	constexpr DXGI_FORMAT RG32UI = DXGI_FORMAT_R32G32_UINT;
	constexpr DXGI_FORMAT RGB32UI = DXGI_FORMAT_R32G32B32_UINT;
	constexpr DXGI_FORMAT RGBA32UI = DXGI_FORMAT_R32G32B32A32_UINT;

	constexpr DXGI_FORMAT RGB10A2UI = DXGI_FORMAT_R10G10B10A2_UINT;

	//有符号归一化
	constexpr DXGI_FORMAT R8SN = DXGI_FORMAT_R8_SNORM;
	constexpr DXGI_FORMAT RG8SN = DXGI_FORMAT_R8G8_SNORM;
	constexpr DXGI_FORMAT RGBA8SN = DXGI_FORMAT_R8G8B8A8_SNORM;

	constexpr DXGI_FORMAT R16SN = DXGI_FORMAT_R16_SNORM;
	constexpr DXGI_FORMAT RG16SN = DXGI_FORMAT_R16G16_SNORM;
	constexpr DXGI_FORMAT RGBA16SN = DXGI_FORMAT_R16G16B16A16_SNORM;

	//无符号归一化
	constexpr DXGI_FORMAT R8UN = DXGI_FORMAT_R8_UNORM;
	constexpr DXGI_FORMAT RG8UN = DXGI_FORMAT_R8G8_UNORM;
	constexpr DXGI_FORMAT RGBA8UN = DXGI_FORMAT_R8G8B8A8_UNORM;

	constexpr DXGI_FORMAT BGRA8UN = DXGI_FORMAT_B8G8R8A8_UNORM;

	constexpr DXGI_FORMAT R16UN = DXGI_FORMAT_R16_UNORM;
	constexpr DXGI_FORMAT RG16UN = DXGI_FORMAT_R16G16_UNORM;
	constexpr DXGI_FORMAT RGBA16UN = DXGI_FORMAT_R16G16B16A16_UNORM;

	constexpr DXGI_FORMAT RGB10A2UN = DXGI_FORMAT_R10G10B10A2_UNORM;

	//浮点
	constexpr DXGI_FORMAT R16F = DXGI_FORMAT_R16_FLOAT;
	constexpr DXGI_FORMAT RG16F = DXGI_FORMAT_R16G16_FLOAT;
	constexpr DXGI_FORMAT RGBA16F = DXGI_FORMAT_R16G16B16A16_FLOAT;

	constexpr DXGI_FORMAT R32F = DXGI_FORMAT_R32_FLOAT;
	constexpr DXGI_FORMAT RG32F = DXGI_FORMAT_R32G32_FLOAT;
	constexpr DXGI_FORMAT RGB32F = DXGI_FORMAT_R32G32B32_FLOAT;
	constexpr DXGI_FORMAT RGBA32F = DXGI_FORMAT_R32G32B32A32_FLOAT;

	constexpr DXGI_FORMAT RG11B10F = DXGI_FORMAT_R11G11B10_FLOAT;

	//无类型
	constexpr DXGI_FORMAT R8TL = DXGI_FORMAT_R8_TYPELESS;
	constexpr DXGI_FORMAT RG8TL = DXGI_FORMAT_R8G8_TYPELESS;
	constexpr DXGI_FORMAT RGBA8TL = DXGI_FORMAT_R8G8B8A8_TYPELESS;

	constexpr DXGI_FORMAT R16TL = DXGI_FORMAT_R16_TYPELESS;
	constexpr DXGI_FORMAT RG16TL = DXGI_FORMAT_R16G16_TYPELESS;
	constexpr DXGI_FORMAT RGBA16TL = DXGI_FORMAT_R16G16B16A16_TYPELESS;

	constexpr DXGI_FORMAT R32TL = DXGI_FORMAT_R32_TYPELESS;
	constexpr DXGI_FORMAT RG32TL = DXGI_FORMAT_R32G32_TYPELESS;
	constexpr DXGI_FORMAT RGB32TL = DXGI_FORMAT_R32G32B32_TYPELESS;
	constexpr DXGI_FORMAT RGBA32TL = DXGI_FORMAT_R32G32B32A32_TYPELESS;

	constexpr DXGI_FORMAT RGB10A2TL = DXGI_FORMAT_R10G10B10A2_TYPELESS;

	constexpr DXGI_FORMAT R24G8TL = DXGI_FORMAT_R24G8_TYPELESS;
	constexpr DXGI_FORMAT R32G8X24TL = DXGI_FORMAT_R32G8X24_TYPELESS;

	//深度
	constexpr DXGI_FORMAT D16UN = DXGI_FORMAT_D16_UNORM;
	constexpr DXGI_FORMAT D32F = DXGI_FORMAT_D32_FLOAT;

	//深度模板
	constexpr DXGI_FORMAT D24UNS8UI = DXGI_FORMAT_D24_UNORM_S8_UINT;
	constexpr DXGI_FORMAT D32FS8X24UI = DXGI_FORMAT_D32_FLOAT_S8X24_UINT;

	//混合
	constexpr DXGI_FORMAT R24UNX8TL = DXGI_FORMAT_R24_UNORM_X8_TYPELESS;
	constexpr DXGI_FORMAT X24TLG8UI = DXGI_FORMAT_X24_TYPELESS_G8_UINT;

	constexpr DXGI_FORMAT R32FX8X24TL = DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS;
	constexpr DXGI_FORMAT X32TLG8X24UI = DXGI_FORMAT_X32_TYPELESS_G8X24_UINT;

	//未知
	constexpr DXGI_FORMAT UNKNOWN = DXGI_FORMAT_UNKNOWN;

	//获取格式的字节大小
	constexpr uint32_t getByteSize(const DXGI_FORMAT format)
	{
		switch (format)
		{
		case RGBA32TL:
		case RGBA32F:
		case RGBA32UI:
		case RGBA32SI:
			return 16;

		case RGB32TL:
		case RGB32F:
		case RGB32UI:
		case RGB32SI:
			return 12;

		case RGBA16TL:
		case RGBA16F:
		case RGBA16UN:
		case RGBA16UI:
		case RGBA16SN:
		case RGBA16SI:
		case RG32TL:
		case RG32F:
		case RG32UI:
		case RG32SI:
		case R32G8X24TL:
		case D32FS8X24UI:
		case R32FX8X24TL:
		case X32TLG8X24UI:
		case DXGI_FORMAT_Y416:
		case DXGI_FORMAT_Y210:
		case DXGI_FORMAT_Y216:
			return 8;

		case RGB10A2TL:
		case RGB10A2UN:
		case RGB10A2UI:
		case RG11B10F:
		case RGBA8TL:
		case RGBA8UN:
		case DXGI_FORMAT_R8G8B8A8_UNORM_SRGB:
		case RGBA8UI:
		case RGBA8SN:
		case RGBA8SI:
		case RG16TL:
		case RG16F:
		case RG16UN:
		case RG16UI:
		case RG16SN:
		case RG16SI:
		case R32TL:
		case D32F:
		case R32F:
		case R32UI:
		case R32SI:
		case R24G8TL:
		case D24UNS8UI:
		case R24UNX8TL:
		case X24TLG8UI:
		case DXGI_FORMAT_R9G9B9E5_SHAREDEXP:
		case DXGI_FORMAT_R8G8_B8G8_UNORM:
		case DXGI_FORMAT_G8R8_G8B8_UNORM:
		case BGRA8UN:
		case DXGI_FORMAT_B8G8R8X8_UNORM:
		case DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM:
		case DXGI_FORMAT_B8G8R8A8_TYPELESS:
		case DXGI_FORMAT_B8G8R8A8_UNORM_SRGB:
		case DXGI_FORMAT_B8G8R8X8_TYPELESS:
		case DXGI_FORMAT_B8G8R8X8_UNORM_SRGB:
		case DXGI_FORMAT_AYUV:
		case DXGI_FORMAT_Y410:
		case DXGI_FORMAT_YUY2:
			return 4;

		case DXGI_FORMAT_P010:
		case DXGI_FORMAT_P016:
		case DXGI_FORMAT_V408:
			return 3;

		case RG8TL:
		case RG8UN:
		case RG8UI:
		case RG8SN:
		case RG8SI:
		case R16TL:
		case R16F:
		case D16UN:
		case R16UN:
		case R16UI:
		case R16SN:
		case R16SI:
		case DXGI_FORMAT_B5G6R5_UNORM:
		case DXGI_FORMAT_B5G5R5A1_UNORM:
		case DXGI_FORMAT_A8P8:
		case DXGI_FORMAT_B4G4R4A4_UNORM:
		case DXGI_FORMAT_P208:
		case DXGI_FORMAT_V208:
			return 2;

		case R8TL:
		case R8UN:
		case R8UI:
		case R8SN:
		case R8SI:
		case DXGI_FORMAT_A8_UNORM:
		case DXGI_FORMAT_BC2_TYPELESS:
		case DXGI_FORMAT_BC2_UNORM:
		case DXGI_FORMAT_BC2_UNORM_SRGB:
		case DXGI_FORMAT_BC3_TYPELESS:
		case DXGI_FORMAT_BC3_UNORM:
		case DXGI_FORMAT_BC3_UNORM_SRGB:
		case DXGI_FORMAT_BC5_TYPELESS:
		case DXGI_FORMAT_BC5_UNORM:
		case DXGI_FORMAT_BC5_SNORM:
		case DXGI_FORMAT_BC6H_TYPELESS:
		case DXGI_FORMAT_BC6H_UF16:
		case DXGI_FORMAT_BC6H_SF16:
		case DXGI_FORMAT_BC7_TYPELESS:
		case DXGI_FORMAT_BC7_UNORM:
		case DXGI_FORMAT_BC7_UNORM_SRGB:
		case DXGI_FORMAT_AI44:
		case DXGI_FORMAT_IA44:
		case DXGI_FORMAT_P8:
			return 1;

		default:
			return 0;
		}
	}
}

#endif // !_GEAR_CORE_FMT_H_
